name: 'Kuberentes (k8s) cli - kubectl'
description: 'GitHub Action for interacting with kubectl (k8s)'
author: 'Agustin Sacco (agustinsacco)'
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  args:
    description: 'Arguments for the CLI command'
    required: false
  redirect-to:
    description: 'Variable name to redirect CLI output'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Kubectl
      run: .github/actions/kubectl/kubectl.sh
      shell: bash
      env:
        KUBE_VERSION: v1.30.3
        ARGS: ${{ inputs.args }}
